### ISSUE TITLE
国内5g是否支持pixel 5 美版

### ISSUE THREAD

**Issue by vvb6** [ender-zhao/Pixel-5-operator-network-unlock#2]
Hello, 请教一下这个module支持美版pixel5 吗？ 刷入模块后，4G/5G 双连接可用：false，5G可用：false，5G状态：NONE。只有voLTE 是开启的。期待回复，谢谢🙏

**Comment by fuadhdmini** [comment]
Can you also include SEA mbn files? Or can I added my carrier's mbn myself?

**Comment by ender-zhao** [comment]
SA 5G的相关内容还在开发

fuadhdmini ***@***.***> 于 2021年3月13日周六 上午9:04写道：

**Comment by vvb6** [comment]
thanks for the information. will close this issue.

**Comment by ender-zhao** [comment]
目前仅解锁了5G NSA。未测试毫米波

vvb6 ***@***.***> 于 2021年3月14日周日 下午6:49写道：
